#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists and first commit exists. If it exists, 
# create master branch by default
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-branch: error: tigger repository directory .tigger not found"
        exit 1
    elif [ ! -f .tigger/last_commit ]
    then    
        echo "tigger-branch: error: this command can not be run until after the first commit"
        exit 1
    elif [ ! -d .tigger/branches ]
    then
        mkdir .tigger/branches
        mkdir .tigger/branches/master
        rsync -Rr . .tigger/branches/master --exclude .tigger/branches
        echo "master" > .tigger/current_branch
    fi
}

# List current branch names
# show_branches 
show_branches () {
    for dir in .tigger/branches/*
    do
        dir=$(echo "$dir" | sed -E 's/.tigger\/branches\/(.*)/\1/')
        echo "$dir"
    done
}

# Delete branch 
# delete_branch <branch>
delete_branch() {
    if [ ! -d .tigger/branches/"$1" ]
    then 
        echo "tigger-branch: error: branch '"$1"' doesn't exist"
        exit 1
    elif [ "$1" = "master" ]
    then 
        echo "tigger-branch: error: can not delete branch 'master'"
        exit 1
    fi
    rm -rf .tigger/branches/"$1"
    echo "Deleted branch '"$1"'"
}

# Create branch
# create_branch <branch>
create_branch () {
    if [ -d .tigger/branches/"$1" ]
    then 
        echo "tigger-branch: error: branch '"$1"' already exists"
        exit 1
    fi
    mkdir .tigger/branches/"$1"
    rsync -Rr . .tigger/branches/"$1" --exclude .tigger/branches --exclude .tigger/current_branch
}

######################################################################
# Main
######################################################################

# Error check
check_tigger

# Case 1: tigger-branch <branch>
if [ ! -z "$1" ] && [ -z "$2" ]
then        
    create_branch "$1"
# Case 2: tigger-branch -d <branch>
elif [ "$1" = "-d" ] && [ ! -z "$2" ] && [ -z "$3" ]
then
    delete_branch "$2"
# Case 3: tigger-branch
elif [ -z "$1" ] 
then    
    show_branches
# Default: raise error
else 
    echo "usage: tigger-branch [-d] <branch>"
fi
