#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists and first commit exists. If it exists, 
# create master branch by default
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-checkout: error: tigger repository directory .tigger not found"
        exit 1
    elif [ ! -f .tigger/last_commit ]
    then    
        echo "tigger-checkout: error: this command can not be run until after the first commit"
        exit 1
    elif [ ! -d .tigger/branches ]
    then
        mkdir .tigger/branches
        mkdir .tigger/branches/master
        rsync -Rr . .tigger/branches/master --exclude .tigger/branches
    fi
}

# Change to specified branch
# Usage: change_branch <branch>
change_branch () {
    echo "Changed branch"
}

######################################################################
# Main
######################################################################

check_tigger

# Case 1: tigger-branch <branch>
if [ ! -z "$1" ] && [ -z "$2" ]
then        
    change_branch "$1"
# Default: raise error
else 
    echo "usage: tigger-checkout <branch>"
fi


