#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Check if file is in tigger index
check_file_in_index () {
    if [ ! -f .tigger/index/"$1" ]
    then
        echo "tigger-rm: error: '"$1"' is not in the tigger repository"
        exit 1
    fi
}

# Throw error if there is any staging differences
# Usage: check_if_staged <filename>
check_if_staged () {
    if [ -f .tigger/last_commit ]
    then
        last_commit=$(cat .tigger/last_commit)
        if [ ! -f .tigger/"$last_commit"/"$1" ] 
        then 
            echo "tigger-rm: error: '$1' has staged changes in the index"
            exit 1
        fi
        diff=$(diff -r .tigger/"$last_commit/$1" "$1")
        if [ ! -z "$diff" ] 
        then 
            echo "tigger-rm: error: '$1' has staged changes in the index"
            exit 1
        fi
    else 
        echo "tigger-rm: error: '$1' has staged changes in the index"
        exit 1
    fi
}

# Delete file from index and current repository
# Usage: full_delete <filenames...>    
full_delete () {
    for file
    do 
        check_file_in_index "$file"
        rm .tigger/index/"$file"
        if [ -f "$file" ]
        then
            rm "$file"
        fi
    done
}

# Delete file from tigger cache/index
# Usage: cache_delete <filenames...>
cache_delete () {
    for file
    do 
        check_file_in_index "$file"
        rm .tigger/index/"$file"
    done
}

# Delete file from index and current repository with safety check
# Usage: safe_delete <filenames...>    
safe_delete () {
    for file
    do 
        check_file_in_index "$file" 
        check_if_staged "$file"
        rm .tigger/index/"$file"
        if [ -f "$file" ]
        then
            rm "$file"
        fi
    done
}

# Error check: .tigger exists
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-rm: error: tigger repository directory .tigger not found"
        exit 1
    fi
}

######################################################################
# Main
######################################################################

# Error check
check_tigger

# Case 1: tigger-rm --force --cached filenames...
if [ "$1" = "--force" ] && [ "$2" = "--cached" ] && [ ! -z "$3" ]
then    
    shift 2
    cache_delete "$@"
# Case 2: tigger-rm --force filenames...
elif [ "$1" = "--force" ] && [ ! -z "$2" ]
then
    shift 1
    full_delete "$@"
# Case 3: tigger-rm --cached filenames...
elif [ "$1" = "--cached" ] && [ ! -z "$2" ]
then
    shift 1
    cache_delete "$@"
# Case 4: tigger-rm filenames...
else 
    safe_delete "$@"
fi
