#!/bin/dash

if [ ! -d ".tigger" ]
then
    echo "tigger-add: error: tigger repository directory .tigger not found"
    exit 1
fi

for file
do
    # If file is deleted but not from index, remove it without error
    if [ ! -f "$file" ] && [ -f .tigger/index/"$file" ]
    then    
        rm .tigger/index/"$file"
    elif [ -f "$file" ]
    then
        cp $file .tigger/index
    else 
        echo "tigger-add: error: can not open '$file'"
        exit 1
    fi 
done
