#!/bin/dash

if [ -d ".tigger" ]
then
    echo "tigger-init: error: .tigger already exists"
else
    mkdir .tigger
    mkdir .tigger/index .tigger/message
    echo "Initialized empty tigger repository in .tigger"
fi

