#!/bin/dash

if [ ! -d ".tigger" ]
then
    echo "tigger-add: error: tigger repository directory .tigger not found"
    exit 1
fi

for file
do
    if [ ! -f "$file" ]
    then
        echo "tigger-add: error: can not open '$file'"
        exit 1
    fi
    cp $file .tigger/index
done