#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Check if file is in tigger index
check_file_in_index () {
    if [ ! -f .tigger/index/"$1" ]
    then
        echo "tigger-rm: error: '"$1"' is not in the tigger repository"
        exit 1
    fi
}

# # Get last commit
# check_unstaged () {
#     count=0
#     while true
#     do 
#         if [ ! -d ".tigger/$count" ] 
#         then
#             echo $count
#             break
#         fi
#         count=$((count + 1))
#     done
#     count=$((count - 1))
#     if [ $count -ge 0 ]
#     then 
#         diff=$(diff -r .tigger/"$1" .tigger/index)
#         if [ ! -z "$diff" ] 
#         then 
#             echo "tigger-rm: error: 'c' has staged changes in the index"
#             exit 1
#         fi
#     fi
# }

# Delete file from index and current repository
# Usage: full_delete <filenames...>    
full_delete () {
    for file
    do 
        check_file_in_index "$file"
        rm .tigger/index/"$file"
        if [ -f "$file" ]
        then
            rm "$file"
        fi
    done
}

# Delete file from tigger cache/index
# Usage: cache_delete <filenames...>
cache_delete () {
    for file
    do 
        check_file_in_index "$file"
        rm .tigger/index/"$file"
    done
}

# Delete file from index and current repository with safety check
# Usage: safe_delete <filenames...>    
safe_delete () {
    for file
    do 
        check_file_in_index "$file" 
        rm .tigger/index/"$file"
        if [ -f "$file" ]
        then
            rm "$file"
        fi
    done
}

# Error check: .tigger exists
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-rm: error: tigger repository directory .tigger not found"
        exit 1
    fi
}

######################################################################
# Main
######################################################################

# Error check
check_tigger

# Case 1: tigger-rm --force --cached filenames...
if [ "$1" = "--force" ] && [ "$2" = "--cached" ] && [ ! -z "$3" ]
then    
    shift 2
    cache_delete "$@"
# Case 2: tigger-rm --force filenames...
elif [ "$1" = "--force" ] && [ ! -z "$2" ]
then
    shift 1
    full_delete "$@"
# Case 3: tigger-rm --cached filenames...
elif [ "$1" = "--cached" ] && [ ! -z "$2" ]
then
    shift 1
    cache_delete "$@"
# Case 4: tigger-rm filenames...
else 
    echo "NOT DONE"
fi
