#!/bin/dash

# Error check: .tigger exists
if [ ! -d ".tigger" ]
then
    echo "tigger-log: error: tigger repository directory .tigger not found"
    exit 1
fi

for commit in .tigger/[0-9]
do
    message=$(cat $commit/message)
    index=$(echo "$commit" | sed -E 's/.tigger\/([0-9])/\1/')
    echo "$index $message"
done 
