#!/bin/dash

# Error check: .tigger exists
if [ ! -d ".tigger" ]
then
    echo "tigger-log: error: tigger repository directory .tigger not found"
    exit 1
fi

count=0
while true
do 
    if [ -d ".tigger/$count" ] 
    then
        echo "$count .tigger/$count"
        break
    fi
    count=$((count + 1))
done
