#!/bin/dash

# Error check: .tigger exists
if [ ! -d ".tigger" ]
then
    echo "tigger-log: error: tigger repository directory .tigger not found"
    exit 1
fi

log=''

for commit in .tigger/[0-9]
do
    message=$(cat $commit/message)
    index=$(echo "$commit" | sed -E 's/.tigger\/([0-9])/\1/')
    log="$log,$index $message"
done 

echo "$log" | cut -d',' -f2- | tr ',' '\n' | sort  -r