#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists 
check_tigger () {
    if [ -d ".tigger" ]
    then
        echo "tigger-init: error: .tigger already exists"
        exit 1
    fi
}

# Create tigger repository
# Usage: make_tigger
make_tigger () {
    mkdir .tigger
    mkdir .tigger/index .tigger/message .tigger/commits
    echo "Initialized empty tigger repository in .tigger"
}

######################################################################
# Main
######################################################################

# Case 1: tigger-init
if [ -z "$1" ]
then    
    check_tigger
    make_tigger
# Default - raise usage error
else 
    echo "usage: tigger-init"
    exit 1
fi

