#!/bin/dash

# Error check: .tigger exists
if [ ! -d ".tigger" ]
then
    echo "tigger-show: error: tigger repository directory .tigger not found"
    exit 1
fi

#Error check: commit has 1 argument
if [ "$#" -ne 1 ] 
then 
    echo "usage: tigger-show <commit>:<filename>"
    exit 1
fi

commit=$(echo $1 | cut -d':' -f1)
filename=$(echo $1 | cut -d':' -f2)

# Error check: commit exists
if [ ! -d ".tigger/$commit" ]
then
    echo "tigger-show: error: unknown commit '$commit'"
    exit 1
fi

if [ -z "$filename" ] 
then
    echo "usage: tigger-show <commit>:<filename>"
    exit 1
fi

if [ -z "$commit" ] 
then    

    # Error check: file exists in index
    if [ ! -f .tigger/index/"$filename" ]
    then
        echo "tigger-show: error: '$filename' not found in index"
        exit 1
    fi

    cat .tigger/index/"$filename"

else 

    # Error check: file exists in commit
    if [ ! -f .tigger/"$commit"/"$filename" ]
    then
        echo "tigger-show: error: '$filename' not found in commit $commit"
        exit 1
    fi
    
    cat .tigger/"$commit"/"$filename"

fi



