#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists 
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-commit: error: tigger repository directory .tigger not found"
        exit 1
    fi
}

# Return the next new commit number
# Usage: get_new_commit 
get_new_commit () {
    if [ -f .tigger/last_commit ] 
    then
        last_commit=$(cat .tigger/last_commit)
        echo "$((last_commit + 1))"
    else
        echo "0"
    fi
}

# Check if there are any current changes between given last commit and index
# Usage: check_last_commit_diff 
check_last_commit_diff () {
    if [ -f .tigger/last_commit ] 
    then
        last_commit=$(cat .tigger/last_commit)
        diff=$(diff -r .tigger/"$last_commit" .tigger/index)
        if [ -z "$diff" ] 
        then 
            echo "nothing to commit"
            exit 1
        fi
    fi
}

# Given a commit number, commit the changes in tigger
# Usage: commit <commit> <message>
commit () {
    mkdir ".tigger/$1"
    for file in .tigger/index/*
    do 
        if [ -f "$file" ] 
        then 
            cp "$file" .tigger/"$1"
        fi
    done
    echo "$2" > .tigger/message/"$1"
    echo "$1" > .tigger/last_commit
    echo "Committed as commit $1"
}

# Add files to index (tigger-add functionality)
add_to_index () {
    for file in *
    do
        if [ ! -f "$file" ]
        then
            echo "tigger-commit: error: can not open '$file'"
            exit 1
        fi
        cp $file .tigger/index
    done
}

######################################################################
# Main
######################################################################

check_tigger

new_commit=$(get_new_commit)

# Case 1: tigger-commit -a -m <message>
if [ "$1" = "-a" ] && [ "$2" = "-m" ] && [ ! -z "$3" ]
then    
    add_to_index
    check_last_commit_diff
    commit "$new_commit" "$2"
# Case 2: tigger-commit -m <message>
elif [ "$1" = "-m" ] && [ ! -z "$2" ]
then
    check_last_commit_diff
    commit "$new_commit" "$2"
# Default - raise usage error
else 
    echo "usage: tigger-commit [-a] -m commit-message"
    exit 1
fi

