#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Get last commit number if there is one otherwise return -1
# Usage: get_last_commit
get_last_commit () {
    last_commit=$(find .tigger/commits -maxdepth 1 -mindepth 1 | sed -E 's/.tigger\/commits\/(.*)/\1/g' | tr ' ' '\n' | sort | tail -n 1)
    if [ -z "$last_commit" ]
    then 
        echo "-1"
    else
        echo "$last_commit"
    fi
}

# Error check: .tigger exists and first commit exists. If it exists, 
# create master branch by default
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-branch: error: tigger repository directory .tigger not found"
        exit 1
    fi
    last_commit=$(get_last_commit)
    if [ "$last_commit" = -1 ]
    then    
        echo "tigger-branch: error: this command can not be run until after the first commit"
        exit 1
    fi
}

# List current branch names
# show_branches 
show_branches () {
    for dir in .tigger/branches/*
    do
        dir=$(echo "$dir" | sed -E 's/.tigger\/branches\/(.*)/\1/')
        echo "$dir"
    done
}

# Delete branch 
# delete_branch <branch>
delete_branch() {
    if [ ! -d .tigger/branches/"$1" ]
    then 
        echo "tigger-branch: error: branch '$1' doesn't exist"
        exit 1
    elif [ "$1" = "master" ]
    then 
        echo "tigger-branch: error: can not delete branch 'master'"
        exit 1
    fi
    rm -rf .tigger/branches/"$1"
    echo "Deleted branch '$1'"
}

# Retrieves the last commit of the specified branch
# Usage: get_last_commit_of_branch <branch>
get_last_commit_of_branch () {
    log=$(cat .tigger/branches/"$1"/log)
    echo "$log" | tail -n 1
}

# Create branch
# create_branch <branch>
create_branch () {
    if [ -d .tigger/branches/"$1" ]
    then 
        echo "tigger-branch: error: branch '$1' already exists"
        exit 1
    fi
    mkdir .tigger/branches/"$1"
    mkdir .tigger/branches/"$1"/files
    mkdir .tigger/branches/"$1"/index
    curr_branch=$(cat .tigger/current_branch)
    echo "$(get_last_commit_of_branch "$curr_branch")" > .tigger/branches/"$1"/log
}

######################################################################
# Main
######################################################################

# Error check
check_tigger

# Case 1: tigger-branch <branch>
if [ -n "$1" ] && [ -z "$2" ]
then        
    create_branch "$1"
# Case 2: tigger-branch -d <branch>
elif [ "$1" = "-d" ] && [ -n "$2" ] && [ -z "$3" ]
then
    delete_branch "$2"
# Case 3: tigger-branch
elif [ -z "$1" ] 
then    
    show_branches
# Default: raise error
else 
    echo "usage: tigger-branch [-d] <branch>"
fi
