#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists and first commit exists. If it exists, 
# create master branch by default
check_tigger () {
    if [ ! -d ".tigger" ]
    then
        echo "tigger-checkout: error: tigger repository directory .tigger not found"
        exit 1
    elif [ ! -f .tigger/last_commit ]
    then    
        echo "tigger-checkout: error: this command can not be run until after the first commit"
        exit 1
    elif [ ! -d .tigger/branches ]
    then
        mkdir .tigger/branches
        mkdir .tigger/branches/master
        cp -r .tigger/index .tigger/branches/master/index
        rsync -Rr . .tigger/branches/master/files --exclude .tigger
        echo "master" > .tigger/current_branch
    fi
}

# Check if .tigger-checkout is valid from current branch
# usage check_branch <branch>
check_branch () {
    if [ "$(cat .tigger/current_branch)" = "$1" ]
    then 
        echo "Already on '$1'"
        exit 1
    elif [ ! -d .tigger/branches/"$1" ]
    then
        echo "tigger-checkout: error: unknown branch '$1'" 
        exit 1
    fi
}

# Change to specified branch
# Usage: change_branch <branch>
change_branch () {
    # Save state to current branch
    cp -r .tigger/index .tigger/branches/"$(cat .tigger/current_branch)"/index
    rsync -Rr . .tigger/branches/"$(cat .tigger/current_branch)"/files --exclude .tigger
    # Delete state
    rm -rf ./*
    # Load state from specified branch
    cp -r .tigger/branches/"$1"/index .tigger/index
    cp -r .tigger/branches/"$1"/files/* .
    echo "$1" > .tigger/current_branch
    echo "Switched to branch '$1'"
}

######################################################################
# Main
######################################################################

check_tigger

# Case 1: tigger-branch <branch>
if [ "$1" != "" ] && [ -z "$2" ]
then        
    check_branch "$1"
    change_branch "$1"
# Default: raise error
else 
    echo "usage: tigger-checkout <branch>"
fi


# rm -rf * && rm -rf .tigger
# ../tigger-init
# touch a
# ../tigger-add a
# ../tigger-commit -m asdf
# ../tigger-status
# ../tigger-branch asdf
# touch b
# ../tigger-add b
# ../tigger-commit -m fdsa
# ../tigger-checkout asdf

# Also create test case where git commit -am does not work but git add and then commit works

# rm -rf * && rm -rf .tigger
# 2041 tigger-init
# touch a && 2041 tigger-add a && 2041 tigger-commit -m asdf
# 2041 tigger-checkout master
# 2041 tigger-branch b1 && 2041 tigger-checkout b1
# touch b && 2041 tigger-add b && 2041 tigger-commit -m asdf
# 2041 tigger-checkout master
# 2041 tigger-branch b2 && 2041 tigger-checkout b2
# touch c && 2041 tigger-add c && 2041 tigger-commit -m asdf
# 2041 tigger-checkout master
# 2041 tigger-branch b3 && 2041 tigger-checkout b3
# touch d && 2041 tigger-add d && 2041 tigger-commit -m asdf

# rm -rf * && rm -rf .tigger
# ../tigger-init
# touch a && ../tigger-add a && ../tigger-commit -m asdf
# ../tigger-checkout master
# ../tigger-branch b1 && ../tigger-checkout b1
# touch b && ../tigger-add b && ../tigger-commit -m asdf
# ../tigger-checkout master
# ../tigger-branch b2 && ../tigger-checkout b2
# touch c && ../tigger-add c && ../tigger-commit -m asdf
# ../tigger-checkout master
# ../tigger-branch b3 && ../tigger-checkout b3
# touch d && ../tigger-add d && ../tigger-commit -m asdf

# rm -rf * && rm -rf .tigger && ../tigger-init && touch a && ../tigger-add a && ../tigger-commit -m asdf && touch b && ../tigger-checkout master

# rm -rf * && rm -rf .tigger
# 2041 tigger-init
# echo hello >a
# 2041 tigger-add a
# 2041 tigger-commit -m commit-A
# 2041 tigger-branch b1
# echo world >>a
# 2041 tigger-checkout b1

# echo -e "\n\n\n"
# rm -rf * && rm -rf .tigger
# 2041 tigger-init
# echo hello >a
# 2041 tigger-add a
# 2041 tigger-commit -m commit-A
# 2041 tigger-branch b1
# echo world >>a
# 2041 tigger-checkout b1
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-status
# 2041 tigger-checkout master
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-add a
# 2041 tigger-status
# 2041 tigger-checkout b1
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-status
# 2041 tigger-checkout master
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-commit -a -m commit-B
# 2041 tigger-checkout b1
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-status
# 2041 tigger-checkout master
# echo "-----------"
# cat a
# echo "-----------"
# 2041 tigger-status