#!/bin/dash

######################################################################
# Helper Functions
######################################################################

# Error check: .tigger exists 
check_tigger () {
    if [ -d ".tigger" ]
    then
        echo "tigger-init: error: .tigger already exists"
        exit 1
    fi
}

make_tigger () {
    mkdir .tigger
    mkdir .tigger/index .tigger/message .tigger/commits
    echo "Initialized empty tigger repository in .tigger"
}

######################################################################
# Main
######################################################################

check_tigger

# Case 1: tigger-init
if [ -z "$1" ]
then    
    make_tigger
# Default - raise usage error
else 
    echo "usage: tigger-init"
    exit 1
fi

